import { ComicPanel } from "../types";
import {
  getValidPanels,
  loadImage,
  dateSuffix,
  measureTextLines,
  wrapText,
} from "./shared";

// ============================================================
// PDF 导出 — Canvas 渲染 + jsPDF 分页 (200 DPI, dynamic text)
// ============================================================

/**
 * A4 dimensions at 200 DPI — good quality/size balance.
 * 150 DPI produced noticeable artifacts on text; 300 DPI too heavy.
 */
const PDF_DPI = 200;
const PDF_MM_TO_PX = PDF_DPI / 25.4;
const PDF_A4_W_MM = 210;
const PDF_A4_H_MM = 297;
const PDF_PAGE_W = Math.round(PDF_A4_W_MM * PDF_MM_TO_PX); // ~1654px
const PDF_PAGE_H = Math.round(PDF_A4_H_MM * PDF_MM_TO_PX); // ~2339px
const PDF_FONT_FAMILY = "'Microsoft YaHei', 'PingFang SC', 'Noto Sans SC', sans-serif";

/** Render a cover page with title, style, and panel count */
export async function renderPdfCoverPage(
  title: string,
  style: string,
  panelCount: number,
  coverImage: HTMLImageElement | null,
): Promise<HTMLCanvasElement> {
  const canvas = document.createElement("canvas");
  canvas.width = PDF_PAGE_W;
  canvas.height = PDF_PAGE_H;
  const ctx = canvas.getContext("2d")!;

  // Background gradient (light gray → white)
  const gradient = ctx.createLinearGradient(0, 0, 0, PDF_PAGE_H);
  gradient.addColorStop(0, "#f5f5f5");
  gradient.addColorStop(0.4, "#ffffff");
  gradient.addColorStop(1, "#f8f8f8");
  ctx.fillStyle = gradient;
  ctx.fillRect(0, 0, PDF_PAGE_W, PDF_PAGE_H);

  const centerX = PDF_PAGE_W / 2;
  const margin = Math.round(PDF_PAGE_W * 0.08);

  // Cover image (if available) — large, centered, rounded
  if (coverImage) {
    const imgAreaW = PDF_PAGE_W - margin * 2;
    const imgAreaH = Math.round(PDF_PAGE_H * 0.45);
    const imgY = Math.round(PDF_PAGE_H * 0.12);

    ctx.save();
    const radius = 16;
    ctx.beginPath();
    ctx.roundRect(margin, imgY, imgAreaW, imgAreaH, radius);
    ctx.clip();

    // Cover-fit
    const srcA = coverImage.width / coverImage.height;
    const dstA = imgAreaW / imgAreaH;
    let dw: number, dh: number, dx: number, dy: number;
    if (srcA > dstA) {
      dh = imgAreaH;
      dw = dh * srcA;
      dx = margin + (imgAreaW - dw) / 2;
      dy = imgY;
    } else {
      dw = imgAreaW;
      dh = dw / srcA;
      dx = margin;
      dy = imgY + (imgAreaH - dh) / 2;
    }
    ctx.drawImage(coverImage, dx, dy, dw, dh);
    ctx.restore();

    // Subtle border
    ctx.strokeStyle = "#e0e0e0";
    ctx.lineWidth = 2;
    ctx.beginPath();
    ctx.roundRect(margin, imgY, imgAreaW, imgAreaH, radius);
    ctx.stroke();
  }

  // Title
  const titleY = coverImage ? Math.round(PDF_PAGE_H * 0.64) : Math.round(PDF_PAGE_H * 0.38);
  const titleFontSize = Math.round(PDF_PAGE_W * 0.04);
  ctx.fillStyle = "#1a1a1a";
  ctx.font = `bold ${titleFontSize}px ${PDF_FONT_FAMILY}`;
  ctx.textAlign = "center";
  ctx.textBaseline = "middle";
  ctx.fillText(title, centerX, titleY, PDF_PAGE_W - margin * 2);

  // Decorative line under title
  const lineY = titleY + Math.round(titleFontSize * 1.2);
  const lineW = Math.round(PDF_PAGE_W * 0.2);
  ctx.strokeStyle = "#6366f1";
  ctx.lineWidth = 3;
  ctx.beginPath();
  ctx.moveTo(centerX - lineW / 2, lineY);
  ctx.lineTo(centerX + lineW / 2, lineY);
  ctx.stroke();

  // Metadata
  const metaY = lineY + Math.round(PDF_PAGE_H * 0.04);
  const metaFontSize = Math.round(PDF_PAGE_W * 0.016);
  ctx.fillStyle = "#666";
  ctx.font = `${metaFontSize}px ${PDF_FONT_FAMILY}`;
  ctx.textAlign = "center";
  ctx.textBaseline = "middle";
  ctx.fillText(`${style}  ·  ${panelCount} panels  ·  ${dateSuffix()}`, centerX, metaY);

  // Footer
  const footerFontSize = Math.round(PDF_PAGE_W * 0.01);
  ctx.fillStyle = "#bbb";
  ctx.font = `${footerFontSize}px ${PDF_FONT_FAMILY}`;
  ctx.fillText("Generated by Comicpedia", centerX, PDF_PAGE_H - Math.round(PDF_PAGE_H * 0.04));

  return canvas;
}

/** Measure per-cell text height, returning the computed image/text split */
export function computeCellLayout(
  panels: ComicPanel[],
  cols: number,
  rows: number,
  gridW: number,
  gridH: number,
  gap: number,
): { cellW: number; rowImgH: number[]; rowTextH: number[] } {
  const cellW = Math.floor((gridW - gap * (cols - 1)) / cols);
  const textFontSize = Math.round(cellW * 0.028);
  const textLineHeight = Math.round(textFontSize * 1.45);
  const textPadding = Math.round(cellW * 0.06);

  // Temp canvas for text measurement
  const tmpCanvas = document.createElement("canvas");
  const tmpCtx = tmpCanvas.getContext("2d")!;
  tmpCtx.font = `bold ${textFontSize}px ${PDF_FONT_FAMILY}`;

  const maxTextW = cellW - textPadding * 2;
  // Min text height (1 line + padding)
  const minTextH = textLineHeight + Math.round(textPadding * 1.2);

  // Scene uses a smaller font — measure with that
  const sceneFontSize = Math.round(textFontSize * 0.85);
  const sceneLineHeight = Math.round(sceneFontSize * 1.4);

  // Per-panel text heights (dialogue + scene)
  const panelTextHeights = panels.map((p) => {
    let totalH = Math.round(textPadding * 0.6); // top padding
    if (p.dialogue) {
      const lines = measureTextLines(tmpCtx, p.dialogue, maxTextW);
      totalH += lines * textLineHeight;
    }
    if (p.scene && p.scene !== p.dialogue) {
      tmpCtx.font = `${sceneFontSize}px ${PDF_FONT_FAMILY}`;
      const sceneLines = measureTextLines(tmpCtx, p.scene, maxTextW);
      totalH += Math.round(textLineHeight * 0.3); // gap between dialogue and scene
      totalH += sceneLines * sceneLineHeight;
      tmpCtx.font = `bold ${textFontSize}px ${PDF_FONT_FAMILY}`; // restore
    }
    totalH += Math.round(textPadding * 0.6); // bottom padding
    return Math.max(minTextH, totalH);
  });

  // Per-row: max text height in that row; image height = remaining
  const totalRowH = Math.floor((gridH - gap * (rows - 1)) / rows);
  const rowTextH: number[] = [];
  const rowImgH: number[] = [];

  for (let r = 0; r < rows; r++) {
    let maxTH = minTextH;
    for (let c = 0; c < cols; c++) {
      const idx = r * cols + c;
      if (idx < panelTextHeights.length) {
        maxTH = Math.max(maxTH, panelTextHeights[idx]);
      }
    }
    // Cap text to 30% of cell height to keep image dominant
    const cappedTH = Math.min(maxTH, Math.round(totalRowH * 0.3));
    rowTextH.push(cappedTH);
    rowImgH.push(totalRowH - cappedTH);
  }

  return { cellW, rowImgH, rowTextH };
}

/** Render a single content page with 2x2 panel grid */
export async function renderPdfPage(
  panels: ComicPanel[],
  pageIndex: number,
  totalPages: number,
  title: string,
  firstContentPage: boolean,
  panelOffset: number,
): Promise<HTMLCanvasElement> {
  const canvas = document.createElement("canvas");
  canvas.width = PDF_PAGE_W;
  canvas.height = PDF_PAGE_H;
  const ctx = canvas.getContext("2d")!;

  const margin = Math.round(PDF_PAGE_W * 0.045);
  const gap = Math.round(PDF_PAGE_W * 0.012);
  const cols = 2;
  const rows = 2;
  const headerH = Math.round(PDF_PAGE_H * 0.035);
  const pageNumH = Math.round(PDF_PAGE_H * 0.022);

  // White background
  ctx.fillStyle = "#ffffff";
  ctx.fillRect(0, 0, PDF_PAGE_W, PDF_PAGE_H);

  // Page header — title + divider
  let curY = margin;
  const headerFontSize = Math.round(PDF_PAGE_W * 0.015);
  ctx.fillStyle = "#888";
  ctx.font = `${headerFontSize}px ${PDF_FONT_FAMILY}`;
  ctx.textAlign = "left";
  ctx.textBaseline = "middle";
  ctx.fillText(title, margin, curY + headerH * 0.5, PDF_PAGE_W * 0.6);

  // Page number in header (right side)
  ctx.textAlign = "right";
  ctx.fillText(`${pageIndex + 1} / ${totalPages}`, PDF_PAGE_W - margin, curY + headerH * 0.5);

  // Divider
  curY += headerH;
  ctx.strokeStyle = "#e5e5e5";
  ctx.lineWidth = 1;
  ctx.beginPath();
  ctx.moveTo(margin, curY);
  ctx.lineTo(PDF_PAGE_W - margin, curY);
  ctx.stroke();
  curY += gap;

  // Grid dimensions
  const gridW = PDF_PAGE_W - margin * 2;
  const gridH = PDF_PAGE_H - curY - margin - pageNumH;
  const { cellW, rowImgH, rowTextH } = computeCellLayout(panels, cols, rows, gridW, gridH, gap);
  const totalRowH = Math.floor((gridH - gap * (rows - 1)) / rows);

  const textFontSize = Math.round(cellW * 0.028);
  const textLineHeight = Math.round(textFontSize * 1.45);
  const numFontSize = Math.round(cellW * 0.032);
  const badgeR = Math.round(cellW * 0.025);

  for (let i = 0; i < panels.length; i++) {
    const panel = panels[i];
    const col = i % cols;
    const row = Math.floor(i / cols);
    const x = margin + col * (cellW + gap);
    const y = curY + row * (totalRowH + gap);
    const imgH = rowImgH[row];
    const textH = rowTextH[row];

    // Cell background + border
    ctx.fillStyle = "#fafafa";
    ctx.fillRect(x, y, cellW, imgH + textH);
    ctx.strokeStyle = "#1a1a1a";
    ctx.lineWidth = 2;
    ctx.strokeRect(x, y, cellW, imgH + textH);

    // Image area
    if (panel.imageUrl) {
      try {
        const img = await loadImage(panel.imageUrl);
        ctx.save();
        ctx.beginPath();
        ctx.rect(x + 1, y + 1, cellW - 2, imgH - 1);
        ctx.clip();

        const srcAspect = img.width / img.height;
        const dstAspect = cellW / imgH;
        let drawW: number, drawH: number, drawX: number, drawY: number;
        if (srcAspect > dstAspect) {
          drawH = imgH;
          drawW = imgH * srcAspect;
          drawX = x + (cellW - drawW) / 2;
          drawY = y;
        } else {
          drawW = cellW;
          drawH = cellW / srcAspect;
          drawX = x;
          drawY = y + (imgH - drawH) / 2;
        }
        ctx.drawImage(img, drawX, drawY, drawW, drawH);
        ctx.restore();
      } catch {
        ctx.fillStyle = "#f0f0f0";
        ctx.fillRect(x + 1, y + 1, cellW - 2, imgH - 1);
        ctx.fillStyle = "#999";
        ctx.font = `${textFontSize}px ${PDF_FONT_FAMILY}`;
        ctx.textAlign = "center";
        ctx.textBaseline = "middle";
        ctx.fillText("Image unavailable", x + cellW / 2, y + imgH / 2);
      }
    }

    // Panel number badge
    const badgeCx = x + badgeR + 8;
    const badgeCy = y + badgeR + 8;
    // Shadow
    ctx.fillStyle = "rgba(0,0,0,0.3)";
    ctx.beginPath();
    ctx.arc(badgeCx + 1, badgeCy + 1, badgeR, 0, Math.PI * 2);
    ctx.fill();
    // Badge body
    ctx.fillStyle = "#1a1a1a";
    ctx.beginPath();
    ctx.arc(badgeCx, badgeCy, badgeR, 0, Math.PI * 2);
    ctx.fill();
    ctx.strokeStyle = "#fff";
    ctx.lineWidth = 1.5;
    ctx.beginPath();
    ctx.arc(badgeCx, badgeCy, badgeR, 0, Math.PI * 2);
    ctx.stroke();
    ctx.fillStyle = "#fff";
    ctx.font = `bold ${numFontSize}px sans-serif`;
    ctx.textAlign = "center";
    ctx.textBaseline = "middle";
    ctx.fillText(String(panelOffset + i + 1), badgeCx, badgeCy);

    // Divider between image and text
    ctx.strokeStyle = "#1a1a1a";
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(x, y + imgH);
    ctx.lineTo(x + cellW, y + imgH);
    ctx.stroke();

    // Text area
    ctx.fillStyle = "#fff";
    ctx.fillRect(x + 1, y + imgH + 1, cellW - 2, textH - 2);

    if (panel.dialogue || (panel.scene && panel.scene !== panel.dialogue)) {
      const textPad = Math.round(cellW * 0.03);
      const textX = x + textPad;
      let textY = y + imgH + Math.round(textH * 0.1);
      const textMaxW = cellW - textPad * 2;

      // Left accent bar
      ctx.fillStyle = "#6366f1";
      ctx.fillRect(x + 5, y + imgH + 5, 3, textH - 10);

      // Dialogue (bold, primary)
      if (panel.dialogue) {
        const maxDialogueLines = Math.max(1, Math.floor((textH * 0.55) / textLineHeight));
        ctx.fillStyle = "#1a1a1a";
        ctx.font = `bold ${textFontSize}px ${PDF_FONT_FAMILY}`;
        ctx.textAlign = "left";
        ctx.textBaseline = "top";
        const dialogueH = wrapText(ctx, panel.dialogue, textX + 8, textY, textMaxW - 8, textLineHeight, maxDialogueLines);
        textY += dialogueH + Math.round(textLineHeight * 0.2);
      }

      // Scene description (lighter, smaller — below dialogue)
      if (panel.scene && panel.scene !== panel.dialogue) {
        const sceneFontSize = Math.round(textFontSize * 0.85);
        const sceneLineHeight = Math.round(sceneFontSize * 1.4);
        const remainingH = (y + imgH + textH) - textY - Math.round(textH * 0.08);
        const maxSceneLines = Math.max(1, Math.floor(remainingH / sceneLineHeight));
        ctx.fillStyle = "#666";
        ctx.font = `${sceneFontSize}px ${PDF_FONT_FAMILY}`;
        ctx.textAlign = "left";
        ctx.textBaseline = "top";
        wrapText(ctx, panel.scene, textX + 8, textY, textMaxW - 8, sceneLineHeight, maxSceneLines);
      }
    }
  }

  return canvas;
}

/**
 * Generate a multi-page PDF with comic panels.
 * 200 DPI, dynamic text height per row, cover page, PNG rendering.
 */
export async function downloadAsPdf(panels: ComicPanel[], title: string): Promise<void> {
  const { jsPDF } = await import("jspdf");
  const validPanels = getValidPanels(panels);
  if (validPanels.length === 0) throw new Error("No valid images to export");

  const panelsPerPage = 4; // 2x2 grid
  const contentPages = Math.ceil(validPanels.length / panelsPerPage);
  const totalPages = contentPages + 1; // +1 for cover

  const pdf = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  // Cover page
  let coverImg: HTMLImageElement | null = null;
  if (validPanels[0]?.imageUrl) {
    try {
      coverImg = await loadImage(validPanels[0].imageUrl);
    } catch { /* proceed without cover image */ }
  }
  const coverCanvas = await renderPdfCoverPage(title, "Comic", validPanels.length, coverImg);
  pdf.addImage(coverCanvas.toDataURL("image/png"), "PNG", 0, 0, PDF_A4_W_MM, PDF_A4_H_MM);

  // Content pages
  for (let page = 0; page < contentPages; page++) {
    pdf.addPage("a4", "portrait");

    const startIdx = page * panelsPerPage;
    const pagePanels = validPanels.slice(startIdx, startIdx + panelsPerPage);

    const canvas = await renderPdfPage(
      pagePanels,
      page + 1,      // page 1-based (cover is page 0)
      totalPages,
      title,
      page === 0,
      startIdx,       // panel offset for numbering
    );

    // PNG for lossless text quality (compressed by jsPDF internally)
    pdf.addImage(canvas.toDataURL("image/png"), "PNG", 0, 0, PDF_A4_W_MM, PDF_A4_H_MM);
  }

  pdf.save(`${title}_${dateSuffix()}.pdf`);
}
