import { Character, ComicScript, ComicStyle, ContentType, FactPack, NarrativeOutline, NovelMeta, PartialLLMConfig, PoetryGenre, PoetryMeta, WikipediaContent } from "../types";
import { getContentHandler } from "../contentRegistry";
import {
  StreamChunkCallback,
  getLLMConfig,
  callOpenAICompatible,
  callAnthropic,
  callOpenAICompatibleStream,
  callAnthropicStream,
  callOpenAIWithMessages,
  callAnthropicWithMessages,
} from "./client";

/**
 * 流式生成分镜脚本。
 * 当 onChunk 提供时使用 SSE 流式传输，否则回退到非流式调用。
 * 流式失败时自动回退到非流式，保证可靠性。
 */
export async function generateScriptStream(
  topic: string,
  style: ComicStyle,
  panelCount?: number,
  llmOverrides?: PartialLLMConfig,
  contentType?: ContentType,
  poetryGenre?: PoetryGenre,
  poetryMeta?: PoetryMeta,
  character?: Character,
  onChunk?: StreamChunkCallback,
  signal?: AbortSignal,
  novelMeta?: NovelMeta,
  wikipediaContent?: WikipediaContent,
  allowGuideCharacter?: boolean,
  narrativeOutline?: NarrativeOutline,
  factPack?: FactPack,
): Promise<ComicScript> {
  const config = getLLMConfig(llmOverrides);

  // Use contentRegistry for prompt building
  const handler = getContentHandler(contentType);
  const prompt = handler.buildPrompt({
    topic, style, panelCount, poetryGenre, poetryMeta, character, novelMeta, wikipediaContent, allowGuideCharacter, narrativeOutline, factPack,
  });

  let response: string;

  if (onChunk) {
    if (config.provider === "anthropic") {
      response = await callAnthropicStream(prompt, config, onChunk, signal);
    } else {
      response = await callOpenAICompatibleStream(prompt, config, onChunk, signal);
    }
  } else {
    if (config.provider === "anthropic") {
      response = await callAnthropic(prompt, config);
    } else {
      response = await callOpenAICompatible(prompt, config);
    }
  }

  // Use contentRegistry for response parsing
  const script = handler.parseResponse(response);

  if (!script) {
    console.error("[LLM] 无法解析脚本，原始响应前500字符:", response.substring(0, 500));
    throw new Error("无法解析 LLM 返回的脚本");
  }

  return script;
}

/** 生成分镜脚本 */
export async function generateScript(
  topic: string,
  style: ComicStyle,
  panelCount?: number,
  llmOverrides?: PartialLLMConfig,
  contentType?: ContentType,
  poetryGenre?: PoetryGenre,
  poetryMeta?: PoetryMeta,
  character?: Character,
  novelMeta?: NovelMeta,
  wikipediaContent?: WikipediaContent,
  allowGuideCharacter?: boolean,
  narrativeOutline?: NarrativeOutline,
  factPack?: FactPack,
): Promise<ComicScript> {
  const config = getLLMConfig(llmOverrides);

  // Use contentRegistry for prompt building
  const handler = getContentHandler(contentType);
  const prompt = handler.buildPrompt({
    topic, style, panelCount, poetryGenre, poetryMeta, character, novelMeta, wikipediaContent, allowGuideCharacter, narrativeOutline, factPack,
  });

  let response: string;
  if (config.provider === "anthropic") {
    response = await callAnthropic(prompt, config);
  } else {
    response = await callOpenAICompatible(prompt, config);
  }

  // Use contentRegistry for response parsing
  const script = handler.parseResponse(response);

  if (!script) {
    console.error("[LLM] 无法解析脚本，原始响应前500字符:", response.substring(0, 500));
    throw new Error("无法解析 LLM 返回的脚本");
  }

  return script;
}

// ============================================================
// Topic Research — Pre-scripting knowledge expansion
// ============================================================

/** Topic research result */
export interface TopicResearchResult {
  /** Original user input */
  originalTopic: string;
  /** Expanded description generated by LLM */
  expandedDescription: string;
  /** Key facts and concepts identified */
  keyFacts: string[];
  /** Suggested narrative angle (primary, for backward compat) */
  narrativeAngle: string;
  /** Multiple narrative angle candidates with relevance scores (P2 enhancement) */
  narrativeAngles?: Array<{
    angle: string;
    relevance: number;  // 1-10
    rationale: string;
  }>;
  /** Hierarchical knowledge map (P2 enhancement) */
  knowledgeMap?: {
    core: string[];      // 核心概念（必须覆盖）
    sub: string[];       // 子概念（按面板数裁剪）
    related: string[];   // 关联概念（延伸阅读）
  };
}

/**
 * Call LLM to research and expand a topic before script generation.
 * Uses system prompt + few-shot + low temperature for accuracy.
 * Similar to generateCharacterProfile() but for topics.
 */
export async function generateTopicResearch(
  topic: string,
  llmOverrides?: PartialLLMConfig,
): Promise<TopicResearchResult> {
  const config = getLLMConfig(llmOverrides);

  const systemPrompt = `You are a rigorous knowledge researcher. Your task is to analyze a user-provided topic and output a structured JSON description that will be used to generate an accurate educational comic.

Core rules:
1. For well-known concepts/technologies/people: provide factually accurate descriptions based on established knowledge
2. For obscure or niche topics: describe what it is based on available context, or honestly state that information is limited
3. For ambiguous terms: prioritize the most common/notable interpretation, but note alternatives
4. NEVER hallucinate or fabricate facts — if you're unsure, say so explicitly
5. Output ONLY valid JSON, no other text, no markdown code blocks
6. All text output must be in Simplified Chinese (简体中文)

JSON format:
{
  "expandedDescription": "2-4 sentences: what this topic IS, its significance, and core mechanism/concept",
  "keyFacts": ["fact1", "fact2", ...],
  "narrativeAngle": "Primary recommended angle (backward compat)",
  "narrativeAngles": [
    {"angle": "角度描述", "relevance": 8, "rationale": "为什么这个角度适合漫画叙事"},
    {"angle": "备选角度", "relevance": 6, "rationale": "适合什么场景"}
  ],
  "knowledgeMap": {
    "core": ["必须覆盖的核心概念1", "核心概念2"],
    "sub": ["可选的子概念1", "子概念2"],
    "related": ["延伸关联1", "关联2"]
  }
}`;

  const fewShotUser1 = `主题: Transformer 注意力机制`;
  const fewShotAssistant1 = JSON.stringify({
    expandedDescription: "Transformer是2017年由Google Brain团队（Ashish Vaswani等人）提出的神经网络架构，其核心创新是自注意力机制（Self-Attention）。它通过Query、Key、Value三组向量的点积运算来计算序列中各元素之间的关联权重，彻底取代了RNN的循环结构，实现了并行计算和长距离依赖建模。",
    keyFacts: [
      "2017年论文\"Attention Is All You Need\"提出",
      "核心公式：Attention(Q,K,V) = softmax(QK^T/√d_k)V",
      "Multi-Head Attention：多组Q/K/V并行捕获不同维度的关联",
      "位置编码（Positional Encoding）补充序列顺序信息",
      "GPT、BERT、ChatGPT等模型的基础架构"
    ],
    narrativeAngle: "历史人物引入：从Vaswani团队面临RNN瓶颈的困境讲起，逐步拆解Q/K/V机制",
    narrativeAngles: [
      { angle: "历史人物引入：从Vaswani团队面临RNN瓶颈的困境讲起", relevance: 9, rationale: "有明确的发明者和历史背景，人物故事感强" },
      { angle: "生活类比：把注意力机制比作课堂上老师点名提问", relevance: 7, rationale: "适合低龄受众，直觉理解" },
      { angle: "技术演进：RNN→LSTM→Transformer的进化路径", relevance: 6, rationale: "适合有基础的受众，展示技术脉络" }
    ],
    knowledgeMap: {
      core: ["自注意力机制（Q/K/V）", "Scaled Dot-Product Attention"],
      sub: ["Multi-Head Attention", "位置编码", "Encoder-Decoder结构"],
      related: ["GPT系列", "BERT", "Vision Transformer"]
    }
  }, null, 2);

  const fewShotUser2 = `主题: OpenClaw`;
  const fewShotAssistant2 = JSON.stringify({
    expandedDescription: "OpenClaw是一个开源的机器人灵巧手（Dexterous Hand）项目，旨在降低机器人抓取研究的硬件门槛。它提供了低成本、可3D打印的机械手设计方案，配合开源的控制软件和仿真环境，让研究者和爱好者能以较低成本搭建具备多自由度抓取能力的机器人手。",
    keyFacts: [
      "开源机器人灵巧手项目，可3D打印制造",
      "目标是降低灵巧操作研究的硬件成本门槛",
      "包含机械设计、电子控制、软件仿真的完整方案",
      "支持强化学习等AI方法进行抓取策略训练",
      "属于具身智能（Embodied AI）领域的重要工具"
    ],
    narrativeAngle: "从\"机器人为什么笨手笨脚\"的生活观察引入，展示OpenClaw如何让机器人学会灵巧抓取",
    narrativeAngles: [
      { angle: "生活观察：为什么机器人笨手笨脚？", relevance: 8, rationale: "痛点引入，受众共鸣度高" },
      { angle: "开源精神：如何用3D打印造一只机器手", relevance: 7, rationale: "Maker文化切入，适合科技爱好者" }
    ],
    knowledgeMap: {
      core: ["灵巧手硬件设计", "开源低成本方案"],
      sub: ["强化学习抓取策略", "仿真环境训练"],
      related: ["具身智能", "触觉传感", "人形机器人"]
    }
  }, null, 2);

  const userPrompt = `主题: ${topic}`;

  const messages = [
    { role: "system", content: systemPrompt },
    { role: "user", content: fewShotUser1 },
    { role: "assistant", content: fewShotAssistant1 },
    { role: "user", content: fewShotUser2 },
    { role: "assistant", content: fewShotAssistant2 },
    { role: "user", content: userPrompt },
  ];

  let response: string;
  if (config.provider === "anthropic") {
    response = await callAnthropicWithMessages(
      systemPrompt,
      messages.filter((m) => m.role !== "system"),
      config
    );
  } else {
    response = await callOpenAIWithMessages(messages, config);
  }

  const cleaned = response.trim().replace(/^```json?\s*/, "").replace(/\s*```$/, "");

  try {
    const parsed = JSON.parse(cleaned);
    return {
      originalTopic: topic,
      expandedDescription: String(parsed.expandedDescription || ""),
      keyFacts: Array.isArray(parsed.keyFacts) ? parsed.keyFacts.map(String) : [],
      narrativeAngle: String(parsed.narrativeAngle || ""),
      narrativeAngles: Array.isArray(parsed.narrativeAngles)
        ? parsed.narrativeAngles.map((a: Record<string, unknown>) => ({
            angle: String(a.angle || ""),
            relevance: Math.max(1, Math.min(10, Number(a.relevance) || 5)),
            rationale: String(a.rationale || ""),
          })).sort((a: { relevance: number }, b: { relevance: number }) => b.relevance - a.relevance)
        : undefined,
      knowledgeMap: parsed.knowledgeMap && typeof parsed.knowledgeMap === "object"
        ? {
            core: Array.isArray(parsed.knowledgeMap.core) ? parsed.knowledgeMap.core.map(String) : [],
            sub: Array.isArray(parsed.knowledgeMap.sub) ? parsed.knowledgeMap.sub.map(String) : [],
            related: Array.isArray(parsed.knowledgeMap.related) ? parsed.knowledgeMap.related.map(String) : [],
          }
        : undefined,
    };
  } catch (e) {
    console.error("[LLM] Failed to parse topic research JSON:", cleaned.substring(0, 300));
    // Graceful fallback: return the raw topic without expansion
    return {
      originalTopic: topic,
      expandedDescription: topic,
      keyFacts: [],
      narrativeAngle: "",
    };
  }
}

/**
 * Build an enhanced topic string from research result.
 * Used as input for script generation prompt.
 */
export function buildEnhancedTopicFromResearch(research: TopicResearchResult): string {
  const parts = [research.expandedDescription];

  if (research.keyFacts.length > 0) {
    parts.push(`\n必须覆盖的关键知识点：\n${research.keyFacts.map((f, i) => `${i + 1}. ${f}`).join("\n")}`);
  }

  // P2: 使用知识图谱提供分层指导
  if (research.knowledgeMap) {
    const { core, sub } = research.knowledgeMap;
    if (core.length > 0) {
      parts.push(`\n核心概念（每个必须至少用 1 格讲清楚）：${core.join("、")}`);
    }
    if (sub.length > 0) {
      parts.push(`辅助概念（按面板数酌情覆盖）：${sub.join("、")}`);
    }
  }

  // P2: 使用最高相关度的叙事角度
  if (research.narrativeAngles && research.narrativeAngles.length > 0) {
    const best = research.narrativeAngles[0]; // already sorted by relevance
    parts.push(`\n建议叙事角度：${best.angle}（${best.rationale}）`);
  } else if (research.narrativeAngle) {
    parts.push(`\n建议叙事角度：${research.narrativeAngle}`);
  }

  return parts.join("\n");
}

// ============================================================
// Wikipedia Content Summarization
// ============================================================

/**
 * AI 概括 Wikipedia 长文，提取适合漫画创作的精华内容。
 * 将冗长的百科全文压缩为结构化的知识摘要（3000-5000字）。
 */
export async function summarizeWikipediaContent(
  title: string,
  content: string,
  llmOverrides?: PartialLLMConfig,
): Promise<string> {
  const config = getLLMConfig(llmOverrides);

  const prompt = `你是一位专业的科普编辑。请将以下 Wikipedia 百科内容进行概括和润色，提取最适合制作科普漫画的精华内容。

## 百科词条：${title}

## 原始内容
${content}

## 要求
1. **保留核心知识**：定义、原理、关键数据、重要人物、发展历程、应用场景
2. **去除冗余**：删除过于学术的引用注释、重复表述、参见链接、编辑备注
3. **结构化输出**：按逻辑分段（概述、核心原理、发展历程、应用与影响），每段有小标题
4. **语言统一**：全部使用简体中文，通俗易懂，适合大众科普
5. **长度控制**：3000-5000字，信息密度高但不遗漏关键知识点
6. **事实准确**：不添加原文没有的信息，不编造数据

请直接输出概括后的内容，不要添加额外说明：`;

  let response: string;
  if (config.provider === "anthropic") {
    response = await callAnthropic(prompt, config);
  } else {
    response = await callOpenAICompatible(prompt, config);
  }

  return response.trim();
}

/**
 * 调用 LLM 生成参考图的文生图 prompt。
 * 轻量调用：仅返回一段英文图片描述，用于后续文生图模型生成参考图。
 */
export async function generateReferenceImagePrompt(
  topic: string,
  style: ComicStyle,
  llmOverrides?: PartialLLMConfig,
): Promise<string> {
  const config = getLLMConfig(llmOverrides);

  const prompt = `You are an expert at writing image generation prompts. Based on the following comic topic and style, generate a single reference image prompt that captures the main character(s) and visual tone of the comic.

Topic: ${topic}
Style: ${style}

Requirements:
- Output ONLY the image prompt in English, nothing else
- Focus on character appearance, pose, and art style
- Keep it under 200 words
- Make it detailed enough for consistent character generation`;

  let response: string;
  if (config.provider === "anthropic") {
    response = await callAnthropic(prompt, config);
  } else {
    response = await callOpenAICompatible(prompt, config);
  }

  return response.trim();
}
